name: build and test
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.15.0]
    name: OS ${{ matrix.os }} - node ${{ matrix.node-version }}
    steps:
      - name: Cache node_modules directory
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM packages
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Npm test
        run: |
          npm link
          npm test

