name: build and test
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm link
      - run: npm test

