name: npm-publish
on:
  release:
    types: [published]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.15.0

      - name: Check tag version
        id: check_tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag matches expected format."
            echo "::set-output name=tag_match::true"
          fi

      - name: Publish
        if: steps.check_tag.outputs.tag_match == 'true'
        run: ./scripts/publish-npm-gha.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}